### ISSUE TITLE
Moose::Util::MetaRole error

### ISSUE THREAD

**Issue by hmorgil** [sestaton/Chloro#5]
Hi,
I got the following error when i tried to run choloro, do you have any idea of that?
When using Moose::Util::MetaRole, you must pass a Moose class name, role name, metaclass object, or metarole object. You passed main, and this did not resolve to a metaclass or metarole. Maybe you need to call Moose->init_meta to initialize the metaclass first? at /home/z8/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Util/MetaRole.pm line 15
	Moose::Util::MetaRole::apply_metaroles('for', 'main', 'class_metaroles', 'HASH(0x55995d4fd9a0)', 'role_metaroles', 'HASH(0x55995d4d1668)') called at /home/z8/perl5/lib/perl5/Chloro.pm line 27
	Chloro::init_meta('Chloro', 'for_class', 'Moose::Exception::InvalidArgPassedToMooseUtilMetaRole', 'metaclass', undef, 'meta_name', 'meta') called at /home/z8/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/Moose/Exporter.pm line 484
	Chloro::import('Chloro') called at bin/chloro line 7
	main::BEGIN at bin/chloro line 7
	eval {...} at bin/chloro line 7
BEGIN failed--compilation aborted at bin/chloro line 7.

Thanks

**Comment by sestaton** [comment]
Thank you for your interest, but unfortunately, the database this tool relied on is no longer maintained. It would take a lot of work to redesign the tool and I'm not sure there is much interest in this application. I think there are probably better tools out there now, but I can't think of any off-hand.

I'm going to add a note in the README to say that this tool was experimental but is no longer maintained. Sorry for the troubles.

**Comment by hmorgil** [comment]
Thanks for the information ;)
